import {
  CURRENT_THEME_SCHEMA_VERSION,
  parseThemeDocument,
  type ThemeAppearance,
  type ThemeDensity,
  type ThemeDocument,
  type ThemePresetId,
  type ThemeTokens,
} from './theme.schema';

const SYSTEM_DATE = '2026-01-01T00:00:00.000Z';

const industrialTokens = {
  colorBg: '#0B0D10',
  colorBgSecondary: '#101319',
  colorSurface: '#15191F',
  colorSurfaceRaised: '#1C222A',
  colorCard: '#171C23',
  colorMenu: '#0E1116',
  colorHeader: '#101319',
  colorFooter: '#0B0D10',
  colorText: '#F5F7FA',
  colorTextMuted: '#9AA2AD',
  colorBorder: '#2B323C',
  colorInput: '#10151B',
  colorInputText: '#F5F7FA',
  colorInputBorder: '#39424E',
  colorIcon: '#D3D8DF',
  colorBadge: '#2B2411',
  colorBadgeText: '#FFE18A',
  colorMarker: '#F6B900',
  colorPrimary: '#F6B900',
  colorPrimaryContrast: '#171104',
  colorSecondary: '#D28B00',
  colorSecondaryContrast: '#1C1200',
  colorAccent: '#FFCB3D',
  colorDanger: '#E5484D',
  colorDangerContrast: '#FFFFFF',
  colorSuccess: '#35B979',
  colorWarning: '#F39C12',
  colorInfo: '#4C9AFF',
  colorButtonPrimary: '#F6B900',
  colorButtonPrimaryText: '#171104',
  colorButtonPrimaryHover: '#FFD248',
  colorButtonSecondary: '#252C35',
  colorButtonSecondaryText: '#F5F7FA',
  colorButtonSecondaryHover: '#343D49',
  colorButtonDanger: '#C93D42',
  colorButtonDangerText: '#FFFFFF',
  colorButtonDangerHover: '#E5484D',
  statusAwaiting: '#F6B900',
  statusInProgress: '#4C9AFF',
  statusWaitingPart: '#EF8B2C',
  statusResolved: '#35B979',
  statusCancelled: '#7E8794',
  priorityLow: '#7E8794',
  priorityNormal: '#4C9AFF',
  priorityHigh: '#F39C12',
  priorityCritical: '#E5484D',
  mapEmpty: '#11151A',
  mapPosture: '#252C35',
  mapActive: '#F6B900',
  mapHighlight: '#FFD248',
  mapSelected: '#FFFFFF',
  mapHeatLow: '#265B49',
  mapHeatMedium: '#A36B12',
  mapHeatHigh: '#C93D42',
  assetMotor: '#F6B900',
  assetReducer: '#AEB5BF',
  batteryCage: '#20252C',
  batteryNylon: '#3E8FEA',
  batteryWhiteConveyor: '#E98224',
  batteryFeedCart: '#8B939E',
  batteryElevator: '#D73F44',
  fontFamilyBody: 'Inter, ui-sans-serif, system-ui, sans-serif',
  fontFamilyHeading: 'Inter, ui-sans-serif, system-ui, sans-serif',
  fontFamilyMono: 'ui-monospace, SFMono-Regular, Consolas, monospace',
  fontScale: '1',
  fontSizeTitle: '2.25rem',
  fontSizeText: '1rem',
  fontSizeXs: '0.75rem',
  fontSizeSm: '0.875rem',
  fontSizeMd: '1rem',
  fontSizeLg: '1.125rem',
  fontSizeXl: '1.375rem',
  fontSize2xl: '1.75rem',
  fontSize3xl: '2.25rem',
  fontWeightRegular: '400',
  fontWeightMedium: '500',
  fontWeightSemibold: '650',
  fontWeightBold: '780',
  lineHeightTight: '1.18',
  lineHeightNormal: '1.5',
  lineHeightRelaxed: '1.7',
  spaceXs: '0.25rem',
  spaceSm: '0.5rem',
  spaceMd: '1rem',
  spaceLg: '1.5rem',
  spaceXl: '2rem',
  space2xl: '3rem',
  controlHeight: '2.75rem',
  touchTarget: '2.75rem',
  layoutMaxWidth: '90rem',
  radiusSm: '0.375rem',
  radiusMd: '0.625rem',
  radiusLg: '0.875rem',
  radiusXl: '1.25rem',
  radiusPill: '999rem',
  borderWidth: '1px',
  shadowSm: '0 1px 2px rgb(0 0 0 / 0.28)',
  shadowMd: '0 12px 30px rgb(0 0 0 / 0.3)',
  shadowLg: '0 24px 70px rgb(0 0 0 / 0.42)',
  backdropBlur: '14px',
  surfaceOpacity: '0.96',
  motionFast: '120ms',
  motionNormal: '200ms',
  motionSlow: '360ms',
} satisfies ThemeTokens;

const classicTokens: ThemeTokens = {
  ...industrialTokens,
  colorBg: '#FFF8E8',
  colorBgSecondary: '#F8EAC8',
  colorSurface: '#FFFDF7',
  colorSurfaceRaised: '#FFFFFF',
  colorCard: '#FFF4D6',
  colorMenu: '#3A2A1A',
  colorHeader: '#FFF9EA',
  colorFooter: '#3A2A1A',
  colorText: '#2A211A',
  colorTextMuted: '#806653',
  colorBorder: '#DCC89B',
  colorInput: '#FFFFFF',
  colorInputText: '#2A211A',
  colorInputBorder: '#C9B37E',
  colorIcon: '#59422F',
  colorBadge: '#F3DFAC',
  colorBadgeText: '#4B351D',
  colorMarker: '#D99600',
  colorPrimary: '#F6B900',
  colorPrimaryContrast: '#2A1E00',
  colorSecondary: '#6A4A2B',
  colorSecondaryContrast: '#FFFFFF',
  colorAccent: '#D99600',
  colorButtonPrimary: '#F6B900',
  colorButtonPrimaryText: '#2A1E00',
  colorButtonPrimaryHover: '#DFA700',
  colorButtonSecondary: '#6A4A2B',
  colorButtonSecondaryText: '#FFFFFF',
  colorButtonSecondaryHover: '#533820',
  colorButtonDanger: '#B9383E',
  colorButtonDangerHover: '#982E33',
  mapEmpty: '#F3E7CA',
  mapPosture: '#E2C980',
  mapActive: '#F6B900',
  mapHighlight: '#D99600',
  mapSelected: '#5A3D20',
  assetMotor: '#D99600',
  assetReducer: '#6A5848',
  batteryCage: '#3C342C',
  shadowSm: '0 1px 3px rgb(73 48 16 / 0.12)',
  shadowMd: '0 12px 30px rgb(73 48 16 / 0.14)',
  shadowLg: '0 24px 64px rgb(73 48 16 / 0.18)',
  backdropBlur: '10px',
  surfaceOpacity: '0.98',
  radiusMd: '0.75rem',
  radiusLg: '1rem',
  radiusXl: '1.5rem',
};

const premiumTokens: ThemeTokens = {
  ...industrialTokens,
  colorBg: '#0D0907',
  colorBgSecondary: '#17100C',
  colorSurface: '#211711',
  colorSurfaceRaised: '#2B1E16',
  colorCard: '#1B130E',
  colorMenu: '#100B08',
  colorHeader: '#130D09',
  colorFooter: '#090604',
  colorText: '#FFF4DC',
  colorTextMuted: '#BDA98F',
  colorBorder: '#4E3928',
  colorInput: '#17100C',
  colorInputText: '#FFF4DC',
  colorInputBorder: '#60472F',
  colorIcon: '#E7D3AE',
  colorBadge: '#3E2B18',
  colorBadgeText: '#F9D88A',
  colorMarker: '#D9A441',
  colorPrimary: '#D9A441',
  colorPrimaryContrast: '#1C1205',
  colorSecondary: '#A66B35',
  colorSecondaryContrast: '#FFF8EA',
  colorAccent: '#F0C66D',
  colorButtonPrimary: '#D9A441',
  colorButtonPrimaryText: '#1C1205',
  colorButtonPrimaryHover: '#F0C66D',
  colorButtonSecondary: '#4A3222',
  colorButtonSecondaryText: '#FFF4DC',
  colorButtonSecondaryHover: '#62432C',
  colorButtonDanger: '#A93639',
  colorButtonDangerHover: '#C6494C',
  statusAwaiting: '#D9A441',
  priorityNormal: '#6C9FD8',
  mapEmpty: '#130D09',
  mapPosture: '#3A281D',
  mapActive: '#D9A441',
  mapHighlight: '#F0C66D',
  mapSelected: '#FFF4DC',
  assetMotor: '#D9A441',
  assetReducer: '#B78D68',
  batteryCage: '#241A14',
  fontFamilyHeading: 'Georgia, Cambria, Times New Roman, serif',
  fontWeightSemibold: '600',
  fontWeightBold: '700',
  radiusSm: '0.25rem',
  radiusMd: '0.5rem',
  radiusLg: '0.75rem',
  radiusXl: '1rem',
  shadowSm: '0 2px 5px rgb(0 0 0 / 0.36)',
  shadowMd: '0 16px 40px rgb(0 0 0 / 0.42)',
  shadowLg: '0 28px 80px rgb(0 0 0 / 0.56)',
  backdropBlur: '18px',
  surfaceOpacity: '0.94',
};

const lightTokens: ThemeTokens = {
  ...industrialTokens,
  colorBg: '#F7F5EF',
  colorBgSecondary: '#ECE9E0',
  colorSurface: '#FFFFFF',
  colorSurfaceRaised: '#FFFFFF',
  colorCard: '#FFFEFA',
  colorMenu: '#FFFFFF',
  colorHeader: '#FFFFFF',
  colorFooter: '#F0EDE5',
  colorText: '#201E1A',
  colorTextMuted: '#68645C',
  colorBorder: '#D8D3C8',
  colorInput: '#FFFFFF',
  colorInputText: '#201E1A',
  colorInputBorder: '#BDB7AA',
  colorIcon: '#4A4741',
  colorBadge: '#FFF0B7',
  colorBadgeText: '#493600',
  colorMarker: '#C48F00',
  colorPrimary: '#E5AA00',
  colorPrimaryContrast: '#221900',
  colorSecondary: '#5B5142',
  colorSecondaryContrast: '#FFFFFF',
  colorAccent: '#C48F00',
  colorDanger: '#C4323A',
  colorSuccess: '#218A58',
  colorWarning: '#C87500',
  colorInfo: '#236FC2',
  colorButtonPrimary: '#E5AA00',
  colorButtonPrimaryText: '#221900',
  colorButtonPrimaryHover: '#C99500',
  colorButtonSecondary: '#E6E1D7',
  colorButtonSecondaryText: '#29261F',
  colorButtonSecondaryHover: '#D5CFC3',
  colorButtonDanger: '#C4323A',
  colorButtonDangerHover: '#A3272E',
  statusAwaiting: '#C99000',
  statusInProgress: '#236FC2',
  statusWaitingPart: '#C87500',
  statusResolved: '#218A58',
  statusCancelled: '#706D66',
  priorityLow: '#706D66',
  priorityNormal: '#236FC2',
  priorityHigh: '#C87500',
  priorityCritical: '#C4323A',
  mapEmpty: '#EAE6DD',
  mapPosture: '#D8D3C8',
  mapActive: '#E5AA00',
  mapHighlight: '#C48F00',
  mapSelected: '#29261F',
  mapHeatLow: '#9ACDB3',
  mapHeatMedium: '#E4B55C',
  mapHeatHigh: '#D96569',
  assetMotor: '#C48F00',
  assetReducer: '#68645C',
  batteryCage: '#292C30',
  shadowSm: '0 1px 3px rgb(45 40 30 / 0.1)',
  shadowMd: '0 12px 30px rgb(45 40 30 / 0.12)',
  shadowLg: '0 24px 60px rgb(45 40 30 / 0.16)',
  backdropBlur: '10px',
  surfaceOpacity: '0.98',
};

const contrastTokens: ThemeTokens = {
  ...industrialTokens,
  colorBg: '#000000',
  colorBgSecondary: '#080808',
  colorSurface: '#101010',
  colorSurfaceRaised: '#1B1B1B',
  colorCard: '#101010',
  colorMenu: '#000000',
  colorHeader: '#000000',
  colorFooter: '#000000',
  colorText: '#FFFFFF',
  colorTextMuted: '#D6D6D6',
  colorBorder: '#737373',
  colorInput: '#000000',
  colorInputText: '#FFFFFF',
  colorInputBorder: '#FFFFFF',
  colorIcon: '#FFFFFF',
  colorBadge: '#332900',
  colorBadgeText: '#FFF36B',
  colorMarker: '#FFF200',
  colorPrimary: '#FFF200',
  colorPrimaryContrast: '#000000',
  colorSecondary: '#FFFFFF',
  colorSecondaryContrast: '#000000',
  colorAccent: '#FFF200',
  colorDanger: '#FF3B3B',
  colorDangerContrast: '#000000',
  colorSuccess: '#40E57A',
  colorWarning: '#FFB020',
  colorInfo: '#48A7FF',
  colorButtonPrimary: '#FFF200',
  colorButtonPrimaryText: '#000000',
  colorButtonPrimaryHover: '#FFF875',
  colorButtonSecondary: '#FFFFFF',
  colorButtonSecondaryText: '#000000',
  colorButtonSecondaryHover: '#DADADA',
  colorButtonDanger: '#FF3B3B',
  colorButtonDangerText: '#000000',
  colorButtonDangerHover: '#FF7676',
  statusAwaiting: '#FFF200',
  statusInProgress: '#48A7FF',
  statusWaitingPart: '#FF8A1F',
  statusResolved: '#40E57A',
  statusCancelled: '#C7C7C7',
  priorityLow: '#C7C7C7',
  priorityNormal: '#48A7FF',
  priorityHigh: '#FFB020',
  priorityCritical: '#FF3B3B',
  mapEmpty: '#080808',
  mapPosture: '#292929',
  mapActive: '#FFF200',
  mapHighlight: '#FFFFFF',
  mapSelected: '#48A7FF',
  mapHeatLow: '#40E57A',
  mapHeatMedium: '#FFB020',
  mapHeatHigh: '#FF3B3B',
  assetMotor: '#FFF200',
  assetReducer: '#FFFFFF',
  batteryCage: '#050505',
  batteryNylon: '#48A7FF',
  batteryWhiteConveyor: '#FF8A1F',
  batteryFeedCart: '#D6D6D6',
  batteryElevator: '#FF3B3B',
  fontScale: '1.08',
  fontWeightRegular: '500',
  fontWeightMedium: '650',
  fontWeightSemibold: '750',
  fontWeightBold: '850',
  borderWidth: '2px',
  shadowSm: '0 0 0 2px rgb(255 255 255 / 0.16)',
  shadowMd: '0 0 0 2px rgb(255 242 0 / 0.22)',
  shadowLg: '0 0 0 3px rgb(255 242 0 / 0.3)',
  backdropBlur: '0px',
  surfaceOpacity: '1',
  motionFast: '0ms',
  motionNormal: '0ms',
  motionSlow: '0ms',
};

export interface ThemePresetMetadata {
  id: ThemePresetId;
  name: string;
  description: string;
  appearance: ThemeAppearance;
  density: Exclude<ThemeDensity, 'custom'>;
  tokens: ThemeTokens;
}

export const THEME_PRESETS = {
  classic: {
    id: 'classic',
    name: 'Mantiqueira Clássico',
    description: 'Amarelo, marrom e creme com identidade institucional.',
    appearance: 'light',
    density: 'comfortable',
    tokens: classicTokens,
  },
  industrial: {
    id: 'industrial',
    name: 'Mantiqueira Industrial',
    description: 'Grafite e amarelo para a operação diária de manutenção.',
    appearance: 'dark',
    density: 'comfortable',
    tokens: industrialTokens,
  },
  premium: {
    id: 'premium',
    name: 'Mantiqueira Premium',
    description: 'Preto, bronze e dourado para uma apresentação sofisticada.',
    appearance: 'dark',
    density: 'comfortable',
    tokens: premiumTokens,
  },
  light: {
    id: 'light',
    name: 'Mantiqueira Light',
    description: 'Superfícies claras para ambientes de alta luminosidade.',
    appearance: 'light',
    density: 'comfortable',
    tokens: lightTokens,
  },
  contrast: {
    id: 'contrast',
    name: 'Mantiqueira Contrast',
    description: 'Contraste reforçado, foco visível e leitura rápida em campo.',
    appearance: 'high-contrast',
    density: 'comfortable',
    tokens: contrastTokens,
  },
} as const satisfies Record<ThemePresetId, ThemePresetMetadata>;

export const THEME_PRESET_LIST: readonly ThemePresetMetadata[] = [
  THEME_PRESETS.classic,
  THEME_PRESETS.industrial,
  THEME_PRESETS.premium,
  THEME_PRESETS.light,
  THEME_PRESETS.contrast,
];

export function getPresetTheme(presetId: ThemePresetId): ThemeDocument {
  const preset = THEME_PRESETS[presetId];
  return parseThemeDocument({
    schemaVersion: CURRENT_THEME_SCHEMA_VERSION,
    id: `preset:${preset.id}`,
    name: preset.name,
    kind: 'preset',
    appearance: preset.appearance,
    density: preset.density,
    tokens: { ...preset.tokens },
    revision: 1,
    createdAt: SYSTEM_DATE,
    updatedAt: SYSTEM_DATE,
    presetId: preset.id,
    archived: false,
    isDefault: preset.id === 'industrial',
  });
}

function customId(): string {
  if (typeof globalThis.crypto?.randomUUID === 'function') {
    return `custom:${globalThis.crypto.randomUUID()}`;
  }
  return `custom:${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}

export function createCustomTheme(
  base: ThemeDocument = getPresetTheme('industrial'),
  name = 'Meu tema personalizado',
): ThemeDocument {
  const now = new Date().toISOString();
  const basePresetId = base.kind === 'preset' ? base.presetId : base.basePresetId;

  return parseThemeDocument({
    ...base,
    schemaVersion: CURRENT_THEME_SCHEMA_VERSION,
    id: customId(),
    name,
    kind: 'custom',
    tokens: { ...base.tokens },
    revision: 0,
    createdAt: now,
    updatedAt: now,
    presetId: undefined,
    basePresetId: basePresetId ?? 'industrial',
    archived: false,
    isDefault: false,
  });
}

export function cloneTheme(theme: ThemeDocument): ThemeDocument {
  return parseThemeDocument({ ...theme, tokens: { ...theme.tokens } });
}
